---
  - name: Ensure group 'elastic' exists
    ansible.builtin.group:
      name: elastic
      state: present
    tags: elastic
  - name: Add the user 'elastic' with a bash shell, appending the group 'elastic' to the user's groups
    ansible.builtin.user:
      name: elastic
      shell: /bin/bash
      groups: elastic
      append: yes
    tags: elastic
  - name: Download .tar.gz Elasticsearch from remote URL
    ansible.builtin.get_url:
      url: "{{ elastic_url}}"
      dest: "/tmp/{{ elastic_distr_name }}"
      mode: 0644
      timeout: 60
      force: true
      validate_certs: false
    register: get_elastic
    until: get_elastic is succeeded
    tags: elastic
  - name: Create directrory for Elasticsearch
    ansible.builtin.file:
      state: directory
      owner: elastic
      group: elastic
      mode: 0755
      path: "{{ elastic_home }}"
    tags: elastic
  - name: Extract Elasticsearch in the installation directory
    become: true
    become_user: elastic
    ansible.builtin.unarchive:
      copy: false
      src: "/tmp/{{ elastic_distr_name }}"
      dest: "{{ elastic_home }}"
      extra_opts: [--strip-components=1]
      creates: "{{ elastic_home }}/bin/elasticsearch"
    tags:
      - skip_ansible_lint
      - elastic
  - name: Set environment Elastic
    become: yes
    template:
      src: templates/elk.sh.j2
      dest: /etc/profile.d/elk.sh
    tags: elastic
  - name: Update elastic config host IP
    become: true
    become_user: elastic
    ansible.builtin.lineinfile:
      path: "{{ elastic_home }}/config/elasticsearch.yml"
      regexp: '^#network.host: 192.168.0.1'
      line: 'network.host: 0.0.0.0'
      mode: 0600
    tags: elastic
